#!/bin/python
import requests
import re
import sys

DATA = ""

def debian():
	global DATA
	try:
		req = requests.get(f"https://packages.debian.org/stable/allpackages")
		data = req.text
		if req.status_code == 404:
			raise Exception("404 File not found")
	except Exception as e:
		print("Couldn't pull. Error: ",str(e))
	else:
		ref_data = data.split('<dl>')[1].split('</dl>')[0]
#		cut unwanted unicode by placing regexes here. This is important
		sp_reg = r' \[<.*\]'
		if re.search(sp_reg, ref_data):
			ref_data = re.sub(sp_reg, '', ref_data)
		ref_data = re.sub(r"(<dt>.*'>)", '{\n\t"packageName": "', ref_data)
		ref_data = re.sub(r"(<\/a> \()", '",\n\t"version": "', ref_data)
		ref_data = re.sub(r"(\)<\/dt>)", '",', ref_data)
		ref_data = re.sub(r"(<dd[^>]*>)", '\t"description": "', ref_data)
		ref_data = re.sub(r"<\/dd>",'"\n},',ref_data)
		DATA = open('Debian_Buster_List.json', 'w')
		DATA.write('['+ref_data+'{}\n]')
		DATA.close()

def pds(q):
	global DATA
	try:
		req = requests.get(f"https://raw.githubusercontent.com/linux-on-ibm-z/PDS/master/distro_data/{q}")
		data = req.text
		if req.status_code == 404:
			raise Exception("404 File not found")
	except Exception as e:
		print("Couldn't pull. Error: ",str(e))
	else:
		DATA = open(f'{q}', 'w')
		DATA.write(data)
		DATA.close()

if __name__ == "__main__":
	try:	
		file = sys.argv[1]
		if re.match(r'.*\.json', file):
			print(f"Extracting {file} from PDS data ... ")
			pds(file)
		elif file == 'Debian' or file == 'debian':
			print(f"Extracting {file} data ... ")
			debian()
		else:
			raise
	except:
		print(
			"Usage:\n./package_build <exact_file_name.json>\n\t\t\t[if data is from PDS]"
			"\n./package_build debian\n\t\t\t[if data is from Debian]"
			"\n./package_build\n\t\t\t[for displaying this help]\n"
			"Example:\n./package_build RHEL_8_Package_List.json\n./package_build debian")
	else:
		print("Thanks for using SDT!")
